spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    context-path: /api
